//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordleWpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordleWpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aback
        ///abase
        ///abate
        ///abbey
        ///abbot
        ///abhor
        ///abide
        ///abled
        ///abode
        ///abort
        ///about
        ///above
        ///abuse
        ///abyss
        ///acorn
        ///acrid
        ///actor
        ///acute
        ///adage
        ///adapt
        ///adept
        ///admin
        ///admit
        ///adobe
        ///adopt
        ///adore
        ///adorn
        ///adult
        ///affix
        ///afire
        ///afoot
        ///afoul
        ///after
        ///again
        ///agape
        ///agate
        ///agent
        ///agile
        ///aging
        ///aglow
        ///agony
        ///agora
        ///agree
        ///ahead
        ///aider
        ///aisle
        ///alarm
        ///album
        ///alert
        ///algae
        ///alibi
        ///alien
        ///align
        ///alike
        ///alive
        ///allay
        ///alley
        ///allot
        ///allow
        ///alloy
        ///aloft
        ///alone
        ///along
        ///aloof
        ///aloud
        ///alpha
        ///altar
        ///alter
        ///amass
        ///amaze
        ///amber
        ///amble
        ///amend
        ///amiss
        ///amity
        ///among
        ///ample
        ///amply
        ///amuse
        ///angel
        ///anger
        ///angle
        ///angry
        ///angst
        ///anime
        ///an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnswerWordList {
            get {
                return ResourceManager.GetString("AnswerWordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aahed
        ///aalii
        ///aargh
        ///abaca
        ///abaci
        ///aback
        ///abaft
        ///abaka
        ///abamp
        ///abase
        ///abash
        ///abate
        ///abaya
        ///abbas
        ///abbes
        ///abbey
        ///abbot
        ///abeam
        ///abele
        ///abets
        ///abhor
        ///abide
        ///abled
        ///abler
        ///ables
        ///abmho
        ///abode
        ///abohm
        ///aboil
        ///aboma
        ///aboon
        ///abort
        ///about
        ///above
        ///abris
        ///abuse
        ///abuts
        ///abuzz
        ///abyes
        ///abysm
        ///abyss
        ///acari
        ///acerb
        ///aceta
        ///ached
        ///aches
        ///achoo
        ///acids
        ///acidy
        ///acing
        ///acini
        ///ackee
        ///acmes
        ///acmic
        ///acned
        ///acnes
        ///acock
        ///acold
        ///acorn
        ///acred
        ///acres
        ///acrid
        ///acted
        ///actin
        ///actor
        ///acute
        ///acyls
        ///adage
        ///adapt
        ///addax
        ///added
        ///adder
        ///addle
        ///adeem
        ///adept
        ///adieu
        ///adios
        ///adits
        ///adman
        ///admen
        ///admit
        ///admix
        ///adobe
        ///adobo
        ///adopt
        ///ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidWordList {
            get {
                return ResourceManager.GetString("ValidWordList", resourceCulture);
            }
        }
    }
}
